import { PortalHeader } from "@/components/PortalHeader";
import { StatusPill } from "@/components/StatusPill";
import { trpc } from "@/lib/trpc";
import { ASSET_STATUS_OPTIONS, PAGE_STATUS_OPTIONS } from "@shared/portal";
import { FileImage, KeyRound, ListPlus, Loader2, PencilLine, Save, ShieldCheck } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";

const blankPage = { id: undefined as number | undefined, pageNumber: "", title: "", chapter: "", layoutStatus: "排版中", assetStatus: "待製作", notes: "", pngUrl: "", sortOrder: 0 };
const blankUpdate = { id: undefined as number | undefined, displayDate: "", scope: "", updateType: "", summary: "", affectedPages: "", status: "待確認" };
const blankWeekly = { id: undefined as number | undefined, weekOf: "", completedChapters: "", completedPages: "", latestPageOrder: "", newConfirmations: "", resolvedItems: "", versionChanges: "", nextStage: "" };

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return <label className="block"><span className="mb-1.5 block text-[11px] font-semibold tracking-[0.1em] text-[#766c61]">{label}</span>{children}</label>;
}

const inputClass = "w-full border border-[#d9cfc3] bg-[#fffdf9] px-3 py-2.5 text-sm text-[#312b25] outline-none transition focus:border-[#8d3131] focus:ring-2 focus:ring-[#8d3131]/10";

export default function Admin() {
  const utils = trpc.useUtils();
  const { data, isLoading } = trpc.portal.adminData.useQuery();
  const [pageForm, setPageForm] = useState(blankPage);
  const [updateForm, setUpdateForm] = useState(blankUpdate);
  const [weeklyForm, setWeeklyForm] = useState(blankWeekly);

  const invalidate = async () => {
    await Promise.all([utils.portal.adminData.invalidate(), utils.portal.dashboard.invalidate()]);
  };
  const pageMutation = trpc.portal.savePage.useMutation({ onSuccess: async () => { toast.success("頁面資料已儲存"); setPageForm(blankPage); await invalidate(); }, onError: (error) => toast.error(error.message) });
  const updateMutation = trpc.portal.saveUpdate.useMutation({ onSuccess: async () => { toast.success("更新紀錄已儲存"); setUpdateForm(blankUpdate); await invalidate(); }, onError: (error) => toast.error(error.message) });
  const weeklyMutation = trpc.portal.saveWeeklySnapshot.useMutation({ onSuccess: async () => { toast.success("週進度已儲存"); setWeeklyForm(blankWeekly); await invalidate(); }, onError: (error) => toast.error(error.message) });

  useEffect(() => {
    if (data?.pages?.length && pageForm.sortOrder === 0 && !pageForm.id) setPageForm((form) => ({ ...form, sortOrder: Math.max(...data.pages.map((page) => page.sortOrder)) + 1 }));
  }, [data?.pages]);

  if (isLoading || !data) return <div className="grid min-h-screen place-items-center bg-[#f5f1eb]"><Loader2 className="h-7 w-7 animate-spin text-[#8d3131]" /></div>;

  return (
    <div className="min-h-screen bg-[#f5f1eb] text-[#292621]"><PortalHeader /><main className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><div className="flex flex-col gap-5 border-b border-[#ded5c9] pb-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold tracking-[0.18em] text-[#8d3131]">ADMINISTRATION</p><h1 className="mt-3 font-serif text-4xl">專案資料管理</h1><p className="mt-3 max-w-2xl leading-7 text-[#746a5f]">此處可維護逐頁工作紀錄、PNG mapping、更新紀錄、每週進度與存取白名單；委託方入口會即時使用這些資料。</p></div><div className="flex items-center gap-2 border border-[#cabdaf] bg-[#fffaf4] px-3 py-2 text-sm text-[#6b5d50]"><ShieldCheck className="h-4 w-4 text-[#8d3131]" /> 僅限管理員</div></div>

      <div className="mt-8 grid gap-7 xl:grid-cols-[1fr_1.2fr]">
        <section className="border border-[#ded5c9] bg-[#fffdf9] p-5 sm:p-7"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold tracking-[0.15em] text-[#8d3131]">PAGES</p><h2 className="mt-2 font-serif text-2xl">逐頁工作紀錄</h2></div><ListPlus className="h-6 w-6 text-[#8d3131]" /></div>
          <div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="載入既有頁面"><select className={inputClass} value={pageForm.id ?? "new"} onChange={(event) => { const found = data.pages.find((page) => page.id === Number(event.target.value)); setPageForm(found ? { id: found.id, pageNumber: found.pageNumber, title: found.title, chapter: found.chapter, layoutStatus: found.layoutStatus, assetStatus: found.assetStatus, notes: found.notes || "", pngUrl: found.pngUrl || "", sortOrder: found.sortOrder } : blankPage); }}><option value="new">新增頁面</option>{data.pages.map((page) => <option key={page.id} value={page.id}>{page.pageNumber}｜{page.title}</option>)}</select></Field><Field label="工作排序"><input className={inputClass} type="number" value={pageForm.sortOrder} onChange={(event) => setPageForm({ ...pageForm, sortOrder: Number(event.target.value) })} /></Field><Field label="頁碼"><input className={inputClass} value={pageForm.pageNumber} onChange={(event) => setPageForm({ ...pageForm, pageNumber: event.target.value })} placeholder="例如 P14" /></Field><Field label="所屬章節"><input className={inputClass} value={pageForm.chapter} onChange={(event) => setPageForm({ ...pageForm, chapter: event.target.value })} placeholder="例如 第二章" /></Field><div className="sm:col-span-2"><Field label="頁面標題"><input className={inputClass} value={pageForm.title} onChange={(event) => setPageForm({ ...pageForm, title: event.target.value })} /></Field></div><Field label="排版狀況（原始文字）"><input list="layout-statuses" className={inputClass} value={pageForm.layoutStatus} onChange={(event) => setPageForm({ ...pageForm, layoutStatus: event.target.value })} /><datalist id="layout-statuses">{PAGE_STATUS_OPTIONS.map((item) => <option key={item} value={item} />)}</datalist></Field><Field label="資產狀況（原始文字）"><input list="asset-statuses" className={inputClass} value={pageForm.assetStatus} onChange={(event) => setPageForm({ ...pageForm, assetStatus: event.target.value })} /><datalist id="asset-statuses">{ASSET_STATUS_OPTIONS.map((item) => <option key={item} value={item} />)}</datalist></Field><div className="sm:col-span-2"><Field label="PNG mapping URL"><input className={inputClass} type="url" value={pageForm.pngUrl} onChange={(event) => setPageForm({ ...pageForm, pngUrl: event.target.value })} placeholder="https://…/page.png" /></Field></div><div className="sm:col-span-2"><Field label="備註"><textarea className={`${inputClass} min-h-24`} value={pageForm.notes} onChange={(event) => setPageForm({ ...pageForm, notes: event.target.value })} /></Field></div></div>
          <button onClick={() => pageMutation.mutate({ ...pageForm, notes: pageForm.notes || null, pngUrl: pageForm.pngUrl || null })} disabled={pageMutation.isPending} className="mt-6 inline-flex items-center gap-2 bg-[#292621] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[#8d3131] disabled:opacity-50"><Save className="h-4 w-4" />儲存頁面資料</button>
        </section>

        <section className="border border-[#ded5c9] bg-[#fffdf9] p-5 sm:p-7"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold tracking-[0.15em] text-[#8d3131]">CURRENT RECORDS</p><h2 className="mt-2 font-serif text-2xl">目前頁面資料</h2></div><FileImage className="h-6 w-6 text-[#8d3131]" /></div><div className="mt-6 max-h-[600px] divide-y divide-[#e3dbd1] overflow-auto border-y border-[#e3dbd1]">{data.pages.length ? data.pages.map((page) => <button key={page.id} onClick={() => setPageForm({ id: page.id, pageNumber: page.pageNumber, title: page.title, chapter: page.chapter, layoutStatus: page.layoutStatus, assetStatus: page.assetStatus, notes: page.notes || "", pngUrl: page.pngUrl || "", sortOrder: page.sortOrder })} className="flex w-full items-center justify-between gap-4 py-4 text-left hover:bg-[#faf6ef]"><div className="min-w-0"><p className="font-serif text-lg text-[#8d3131]">{page.pageNumber} <span className="ml-2 text-base text-[#302b25]">{page.title}</span></p><p className="mt-1 text-xs text-[#746a5f]">排序 {page.sortOrder} · {page.chapter}{page.pngUrl ? " · 已設定 PNG" : ""}</p></div><div className="flex shrink-0 gap-1"><StatusPill label={page.layoutStatus} /><PencilLine className="ml-2 h-4 w-4 text-[#8d3131]" /></div></button>) : <p className="py-12 text-center text-sm text-[#746a5f]">尚無頁面資料。</p>}</div></section>
      </div>

      <div className="mt-7 grid gap-7 xl:grid-cols-2">
        <section className="border border-[#ded5c9] bg-[#fffdf9] p-5 sm:p-7"><p className="text-xs font-semibold tracking-[0.15em] text-[#8d3131]">UPDATE LOG</p><h2 className="mt-2 font-serif text-2xl">更新紀錄</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="載入紀錄"><select className={inputClass} value={updateForm.id ?? "new"} onChange={(event) => { const found = data.updates.find((update) => update.id === Number(event.target.value)); setUpdateForm(found ? { id: found.id, displayDate: found.displayDate, scope: found.scope, updateType: found.updateType, summary: found.summary, affectedPages: found.affectedPages, status: found.status } : blankUpdate); }}><option value="new">新增更新紀錄</option>{data.updates.map((update) => <option key={update.id} value={update.id}>{update.displayDate}｜{update.updateType}</option>)}</select></Field><Field label="日期"><input className={inputClass} value={updateForm.displayDate} onChange={(event) => setUpdateForm({ ...updateForm, displayDate: event.target.value })} placeholder="YYYY/MM/DD" /></Field><Field label="範圍"><input className={inputClass} value={updateForm.scope} onChange={(event) => setUpdateForm({ ...updateForm, scope: event.target.value })} /></Field><Field label="更新類型"><input className={inputClass} value={updateForm.updateType} onChange={(event) => setUpdateForm({ ...updateForm, updateType: event.target.value })} /></Field><Field label="影響頁面"><input className={inputClass} value={updateForm.affectedPages} onChange={(event) => setUpdateForm({ ...updateForm, affectedPages: event.target.value })} placeholder="例如 P14–P20" /></Field><Field label="狀態（原始文字）"><input className={inputClass} value={updateForm.status} onChange={(event) => setUpdateForm({ ...updateForm, status: event.target.value })} /></Field><div className="sm:col-span-2"><Field label="變更摘要"><textarea className={`${inputClass} min-h-28`} value={updateForm.summary} onChange={(event) => setUpdateForm({ ...updateForm, summary: event.target.value })} /></Field></div></div><button onClick={() => updateMutation.mutate(updateForm)} disabled={updateMutation.isPending} className="mt-6 inline-flex items-center gap-2 bg-[#292621] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[#8d3131] disabled:opacity-50"><Save className="h-4 w-4" />儲存更新紀錄</button></section>

        <section className="border border-[#ded5c9] bg-[#fffdf9] p-5 sm:p-7"><p className="text-xs font-semibold tracking-[0.15em] text-[#8d3131]">WEEKLY SNAPSHOT</p><h2 className="mt-2 font-serif text-2xl">每週進度</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="載入週進度"><select className={inputClass} value={weeklyForm.id ?? "new"} onChange={(event) => { const found = data.snapshots.find((snapshot) => snapshot.id === Number(event.target.value)); setWeeklyForm(found ? { id: found.id, weekOf: found.weekOf, completedChapters: found.completedChapters, completedPages: found.completedPages, latestPageOrder: found.latestPageOrder, newConfirmations: found.newConfirmations, resolvedItems: found.resolvedItems, versionChanges: found.versionChanges, nextStage: found.nextStage } : blankWeekly); }}><option value="new">新增週進度</option>{data.snapshots.map((snapshot) => <option key={snapshot.id} value={snapshot.id}>{snapshot.weekOf}</option>)}</select></Field><Field label="週進度日期"><input className={inputClass} value={weeklyForm.weekOf} onChange={(event) => setWeeklyForm({ ...weeklyForm, weekOf: event.target.value })} placeholder="YYYY/MM/DD" /></Field>{[["本週完成章節", "completedChapters"], ["本週完成頁面", "completedPages"], ["目前最新頁序", "latestPageOrder"], ["新增待確認", "newConfirmations"], ["已解決項目", "resolvedItems"], ["本週版本異動", "versionChanges"], ["下一階段", "nextStage"]].map(([label, key]) => <Field key={key} label={label}><textarea className={`${inputClass} min-h-20`} value={weeklyForm[key as keyof typeof weeklyForm] as string} onChange={(event) => setWeeklyForm({ ...weeklyForm, [key]: event.target.value })} /></Field>)}</div><button onClick={() => weeklyMutation.mutate(weeklyForm)} disabled={weeklyMutation.isPending} className="mt-6 inline-flex items-center gap-2 bg-[#292621] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[#8d3131] disabled:opacity-50"><Save className="h-4 w-4" />儲存週進度</button></section>
      </div>

      <section className="mt-7 border border-[#ded5c9] bg-[#fffdf9] p-5 sm:p-7"><div className="flex items-center gap-3"><KeyRound className="h-6 w-6 text-[#8d3131]" /><div><p className="text-xs font-semibold tracking-[0.15em] text-[#8d3131]">ACCESS CONTROL</p><h2 className="mt-1 font-serif text-2xl">單一專案密碼</h2></div></div><p className="mt-5 max-w-3xl leading-7 text-[#746a5f]">目前 Portal 不使用 Manus 帳號、Google 帳號或 Email 白名單。所有持有專案密碼的成員皆可瀏覽工作紀錄與使用本頁資料管理功能；若需停止存取，請由網站設定更新專案密碼並重新通知獲授權成員。</p></section>
    </main></div>
  );
}
